// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPI.Data;

#nullable disable

namespace RestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240225134300_SeedPerson")]
    partial class SeedPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RestAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LauchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("RestAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "São Paulo - Brasil",
                            FirstName = "Ayrton",
                            Gender = "Male",
                            LastName = "Senna"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Anchiano - Italy",
                            FirstName = "Leonardo",
                            Gender = "Male",
                            LastName = "da Vinci"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Porbandar - India",
                            FirstName = "Mahatma",
                            Gender = "Male",
                            LastName = "Gandh"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kentucky - USA",
                            FirstName = "Mohamed",
                            Gender = "Male",
                            LastName = "Gandhi"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Mvezo - South Africa",
                            FirstName = "Nelson",
                            Gender = "Male",
                            LastName = "Mandela"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
